# Generated by Django 2.2.3 on 2019-07-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_auto_20190716_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='dt_movimentacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='tp_porcentagem',
            field=models.CharField(blank=True, choices=[('VALOR1', '0%'), ('VALOR2', '2,68%'), ('VALOR3', '7,07%'), ('VALOR4', '8,51%')], max_length=20, null=True, verbose_name='Tipos de Porcentagens'),
        ),
    ]
