# Generated by Django 2.2.3 on 2019-07-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_auto_20190716_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasaida',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
