# Generated by Django 2.2.3 on 2019-07-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0008_auto_20190717_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='tp_convenio',
            field=models.CharField(blank=True, choices=[('INTERODONTO', 'InterOdonto'), ('ODONTOPREV', 'OdontoPrev'), ('BRADESCO', 'Bradesco'), ('PARTICULAR', 'Particular')], max_length=30, null=True, verbose_name='Tipos de Convênios'),
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='tp_pagamento',
            field=models.CharField(blank=True, choices=[('CREDITO', 'Credito'), ('DEBITO', 'Debito'), ('DINHEIRO', 'Dinheiro')], max_length=30, null=True, verbose_name='Tipos de Pagamentos'),
        ),
    ]
