# Generated by Django 2.2.3 on 2019-07-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0009_auto_20190717_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='paciente',
            field=models.CharField(blank=True, max_length=150, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='profissional',
            field=models.CharField(blank=True, max_length=150, verbose_name='Profissional'),
        ),
    ]
