# Generated by Django 2.2.3 on 2019-07-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0010_auto_20190717_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradasaida',
            options={'ordering': ['dt_movimentacao'], 'verbose_name': 'Tipo de Entrada'},
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='motivo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Motivo da Entrada/Saída'),
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='qt_parcelas',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Parcelas'),
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='tp_porcentagem',
            field=models.CharField(blank=True, choices=[('0', '0%'), ('2,68', '2,68%'), ('7,07', '7,07%'), ('8,51', '8,51%')], max_length=20, null=True, verbose_name='Tipos de Porcentagens'),
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='valor_entr_saida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor'),
        ),
    ]
