# Generated by Django 2.2.3 on 2019-07-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0012_auto_20190730_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='tp_porcentagem',
            field=models.DecimalField(blank=True, choices=[('2,68', '2,68%'), ('7,07', '7,07%'), ('8,51', '8,51%')], decimal_places=2, max_digits=5, null=True, verbose_name='Tipos de Porcentagens'),
        ),
    ]
