# Generated by Django 2.2.3 on 2019-08-01 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0013_auto_20190730_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasaida',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='tp_porcentagem',
            field=models.CharField(blank=True, choices=[('2.68', '2.68%'), ('7.07', '7.07%'), ('8.51', '8.51%')], max_length=10, null=True, verbose_name='Tipos de Porcentagens'),
        ),
    ]
