# Generated by Django 2.2.3 on 2019-08-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0014_auto_20190801_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='color',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
