# Generated by Django 2.2.3 on 2019-08-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0019_auto_20190820_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='dt_movimentacao',
            field=models.DateField(),
        ),
    ]
