# Generated by Django 2.2.3 on 2019-08-20 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0020_auto_20190820_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='dt_movimentacao',
            field=models.DateField(default=datetime.datetime(2019, 8, 20, 10, 51, 7, 326290)),
        ),
    ]
