# Generated by Django 2.2.3 on 2019-08-20 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0024_auto_20190820_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='dt_movimentacao',
            field=models.DateField(default=datetime.datetime(2019, 8, 20, 11, 53, 51, 563593)),
        ),
    ]
