# Generated by Django 2.2.3 on 2019-08-30 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0029_auto_20190823_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='dt_movimentacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
