# Generated by Django 2.2.3 on 2019-09-04 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0033_auto_20190830_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradasaida',
            options={'ordering': ['dt_movimentacao'], 'verbose_name': 'Tipo de Entrada', 'verbose_name_plural': 'Tipos de Entradas'},
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='fkespecialidades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qry_especialidades', to='profissional.Especialidades', verbose_name='Especialidades'),
        ),
    ]
