# Generated by Django 2.2.3 on 2019-09-17 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'tb_om_cidades',
                'ordering': ('nome_cidade',),
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=25, verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'tb_om_especialidades',
            },
        ),
        migrations.CreateModel(
            name='OrgaoEmissor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_orgao_emissor', models.CharField(max_length=64, verbose_name='Orgão Emissor')),
                ('sg_orgao_emissor', models.CharField(max_length=15, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Orgão Emissor',
                'verbose_name_plural': 'Orgãos Emissores',
                'db_table': 'tb_om_orgao_emissor',
            },
        ),
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_profissional', models.CharField(max_length=60, verbose_name='Nome do Profissional')),
                ('cpf_profissional', models.CharField(blank=True, max_length=14, null=True, verbose_name='Número do CPF')),
                ('num_registro_classe', models.IntegerField(blank=True, null=True, verbose_name='Num Conselho')),
                ('cidades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qry_cidades', to='profissional.Cidades', verbose_name='cidade')),
                ('especialdiades', models.ManyToManyField(to='profissional.Especialidades')),
                ('orgao_emissor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qry_orgao_emissores', to='profissional.OrgaoEmissor', verbose_name='Orgão Emissor')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'db_table': 'tb_om_profissionais',
            },
        ),
    ]
