# Generated by Django 2.2.3 on 2019-09-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissionais',
            old_name='especialdiades',
            new_name='especialidades',
        ),
    ]
