# Generated by Django 2.2.3 on 2019-08-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=25, verbose_name='Especialidade')),
            ],
            options={
                'db_table': 'tb_om_especialidades',
            },
        ),
        migrations.DeleteModel(
            name='especialidade',
        ),
        migrations.AddField(
            model_name='profissionais',
            name='especialidade',
            field=models.ManyToManyField(to='profissional.Especialidades'),
        ),
    ]
