# Generated by Django 2.2.3 on 2019-08-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0002_auto_20190819_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidades',
            options={'verbose_name': 'Especialidade', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='profissionais',
            options={'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
    ]
