# Generated by Django 2.2.3 on 2019-08-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0003_auto_20190820_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_uf', models.CharField(max_length=42, verbose_name='Estados')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'tb_om_estados',
            },
        ),
        migrations.CreateModel(
            name='OrgaoEmissor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_orgao_emissor', models.CharField(max_length=64, verbose_name='Orgão Emissor')),
                ('sg_orgao_emissor', models.CharField(max_length=15, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Orgão Emissor',
                'db_table': 'tb_om_orgao_emissor',
            },
        ),
        migrations.AddField(
            model_name='profissionais',
            name='num_registro_classe',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reg Conselho da Classe (CRM/CRO/CORE...)'),
        ),
        migrations.AlterField(
            model_name='profissionais',
            name='especialidade',
            field=models.ManyToManyField(related_name='qry_especialidade', to='profissional.Especialidades', verbose_name='Especialidades'),
        ),
        migrations.AddField(
            model_name='profissionais',
            name='orgao_emissor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qry_orgao_emissor', to='profissional.OrgaoEmissor', verbose_name='Orgão Emissor'),
        ),
        migrations.AddField(
            model_name='profissionais',
            name='uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qry_estados', to='profissional.Estados', verbose_name='UF'),
        ),
    ]
