# Generated by Django 2.2.3 on 2019-11-15 00:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_movimentacao', models.DateField(default=datetime.datetime.now)),
                ('profissional', models.CharField(blank=True, max_length=130, verbose_name='Profissional')),
                ('paciente', models.CharField(blank=True, max_length=130, verbose_name='Paciente')),
                ('qt_parcelas', models.IntegerField(default=0, verbose_name='Quantidade de Parcelas')),
                ('valor_entr_saida', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, verbose_name='Valor')),
                ('tp_entrada', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida')], max_length=10, verbose_name='Tipos de Entrada')),
                ('tp_convenio', models.CharField(blank=True, choices=[('INTERODONTO', 'InterOdonto'), ('ODONTOPREV', 'OdontoPrev'), ('BRADESCO', 'Bradesco'), ('PARTICULAR', 'Particular')], max_length=30, null=True, verbose_name='Tipos de Convênios')),
                ('tp_pagamento', models.CharField(blank=True, choices=[('CREDITO', 'Credito'), ('DEBITO', 'Debito'), ('DINHEIRO', 'Dinheiro')], max_length=30, null=True, verbose_name='Tipos de Pagamentos')),
                ('tp_credito', models.CharField(blank=True, choices=[('APRAZO', 'A Prazo')], max_length=20, null=True, verbose_name='Tipos de Créditos')),
                ('tp_porcentagem', models.CharField(blank=True, choices=[('0.00', '0.00%'), ('2.68', '2.68%'), ('7.07', '7.07%'), ('8.51', '8.51%')], default=0.0, max_length=10, null=True, verbose_name='Tipos de Porcentagens')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('motivo', models.CharField(blank=True, max_length=150, verbose_name='Motivo da Entrada/Saída')),
                ('fkespecialidades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qry_especialidades', to='profissional.Especialidades', verbose_name='Especialidades')),
                ('fkprofissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qry_profissionais', to='profissional.Profissionais', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Tipo de Entrada',
                'verbose_name_plural': 'Tipos de Entradas',
                'db_table': 'tb_om_entrada_saida',
                'ordering': ['dt_movimentacao'],
            },
        ),
    ]
