# Generated by Django 2.2.3 on 2019-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradasaida',
            options={'ordering': ['dt_movimentacao'], 'verbose_name': 'Entrada e Saída', 'verbose_name_plural': 'Entradas e Saídas'},
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='tp_credito',
            field=models.CharField(choices=[('APRAZO', 'APrazo')], max_length=20, null=True, verbose_name='Tipos de Créditos'),
        ),
    ]
