# Generated by Django 2.2.3 on 2019-10-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_auto_20191010_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='tp_porcentagem',
            field=models.CharField(blank=True, choices=[('0.00', '0.00%'), ('2.68', '2.68%'), ('7.07', '7.07%'), ('8.51', '8.51%')], max_length=10, null=True, verbose_name='Tipos de Porcentagens'),
        ),
    ]
