# Generated by Django 2.2.3 on 2019-07-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_auto_20190716_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='dt_movimentacao',
            field=models.DateField(blank=True),
        ),
    ]
