# Generated by Django 2.2.3 on 2019-07-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_auto_20190716_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='tp_credito',
            field=models.CharField(blank=True, choices=[('APRAZO', 'A Prazo')], max_length=20, null=True, verbose_name='Tipos de Créditos'),
        ),
    ]
