# Generated by Django 2.2.3 on 2019-10-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_auto_20191010_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='tp_porcentagem',
            field=models.CharField(blank=True, choices=[('0.00', '0.00%'), ('2.68', '2.68%'), ('7.07', '7.07%'), ('8.51', '8.51%')], default=0.0, max_length=10, null=True, verbose_name='Tipos de Porcentagens'),
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='valor_entr_saida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, verbose_name='Valor'),
        ),
    ]
