# Generated by Django 2.2.3 on 2019-07-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0007_entradasaida_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='motivo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Motivo da Entrada ou Saída'),
        ),
    ]
