# Generated by Django 2.2.3 on 2019-08-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0016_remove_entradasaida_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='profissional',
            field=models.CharField(blank=True, max_length=120, verbose_name='Profissional'),
        ),
        migrations.AlterModelTable(
            name='entradasaida',
            table='tb_om_entrada_saida',
        ),
    ]
