# Generated by Django 2.2.3 on 2019-08-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0017_auto_20190819_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='paciente',
            field=models.CharField(blank=True, max_length=130, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='profissional',
            field=models.CharField(blank=True, max_length=130, verbose_name='Profissional'),
        ),
    ]
