# Generated by Django 2.2.3 on 2019-08-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0018_auto_20190819_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='dt_movimentacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
