# Generated by Django 2.2.3 on 2019-08-20 14:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0003_auto_20190820_1137'),
        ('caixa', '0021_auto_20190820_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasaida',
            name='fkprofissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profissional.Profissionais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='dt_movimentacao',
            field=models.DateField(default=datetime.datetime(2019, 8, 20, 11, 36, 57, 981051)),
        ),
    ]
