# Generated by Django 2.2.3 on 2019-08-20 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0022_auto_20190820_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='dt_movimentacao',
            field=models.DateField(default=datetime.datetime(2019, 8, 20, 11, 47, 45, 521329)),
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='fkprofissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissional.Profissionais', verbose_name='Profissional'),
        ),
    ]
