# Generated by Django 2.2.3 on 2019-08-23 14:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0028_auto_20190821_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasaida',
            name='dt_movimentacao',
            field=models.DateField(default=datetime.datetime(2019, 8, 23, 11, 30, 42, 749439)),
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='fkprofissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qry_profissionais', to='profissional.Profissionais', verbose_name='Profissional/Especialidade'),
        ),
    ]
