# Generated by Django 2.2.3 on 2019-08-31 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0009_remove_profissionais_espec'),
        ('caixa', '0031_auto_20190829_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasaida',
            name='fkespecialidades',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profissional.Especialidades', verbose_name='Especialidades'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradasaida',
            name='fkprofissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qry_profissionais', to='profissional.Profissionais', verbose_name='Profissional'),
        ),
    ]
