# Generated by Django 2.2.3 on 2019-08-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_profissional', models.CharField(max_length=60, verbose_name='Nome do Profissional')),
                ('cpf_profissional', models.CharField(blank=True, max_length=14, null=True, verbose_name='Número do CPF')),
            ],
            options={
                'db_table': 'tb_om_profissionais',
            },
        ),
        migrations.CreateModel(
            name='especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=25, verbose_name='Especialidade')),
                ('id_profissional', models.ManyToManyField(to='profissional.Profissionais')),
            ],
            options={
                'db_table': 'tb_om_especialidades',
            },
        ),
    ]
