# Generated by Django 2.2.3 on 2019-08-30 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0008_profissionais_espec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='espec',
        ),
    ]
