# Generated by Django 2.2.3 on 2019-08-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0009_remove_profissionais_espec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='especialidade_detail',
            new_name='especialidade',
        ),
    ]
