# Generated by Django 2.2.3 on 2019-08-31 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0010_auto_20190831_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.ManyToManyField(related_name='qry_especialidades', to='profissional.Especialidades', verbose_name='Especialidades'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='orgao_emissor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qry_orgao_emissores', to='profissional.OrgaoEmissor', verbose_name='Orgão Emissor'),
        ),
    ]
