# Generated by Django 2.2.3 on 2019-08-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0011_auto_20190831_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.ManyToManyField(related_name='qry_profissionais', to='profissional.Especialidades', verbose_name='Especialidades'),
        ),
    ]
