# Generated by Django 2.2.3 on 2019-09-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0012_auto_20190831_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgaoemissor',
            options={'verbose_name': 'Orgão Emissor', 'verbose_name_plural': 'Orgãos Emissores'},
        ),
    ]
